#! /usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
Bundler.require(:default)

require_all 'lib'

$togpath = File.dirname(Pathname.new(__FILE__).realpath)
$debuglevel = 0
load($togpath + '/debuglevel.rb') if File.exist?($togpath + '/debuglevel.rb')

require 'pry' if $debuglevel > 0

if File.exist?(togpath('!tog/runningtests'))
  $settings_path = 'testsettings/'
  $debuglevel = 5
else
  $settings_path = 'settings/'
end

# Setup global vars
$global_menu = []
$set_menu = []
$power_user_help = {}
$set_roots = []
$post_final_tasks = []
$set_catchall_settings = {}

install_if_missing allmods['core']
load_mod_dependencies

while 1 == 1
  load_mod_actions
  # Switch the experience for power users
  if $poweruser
    exit
  else
    cont if $subsequent_pass
    $subsequent_pass = true
  end

  $menu_select = nil

  # If there is a current set - fire it up.
  load_current_set
  unless ARGV[3] == 'quietmode'
    clear_screen
    banner_current_set
  end
  if ARGV[0]
    $poweruser = true
    $menu_select = ARGV[0].downcase
    ARGV[0] = nil
  else
    if $current_set
      $menu_select = main_menu($global_menu, $set_menu)
    else
      $menu_select = main_menu($global_menu)
      puts $menu_select
    end
  end

end
